name: assignments-app

services:
  web:
    build:
      context: ./web-ui
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - assignments
      - submissions
      - db
    # Scaling the application using Docker compose
    # requires an additional proxy service, but could be
    # done with this setup alongside Nginx or other proxy
    # deploy:
    #   endpoint_mode: vip
    #   mode: replicated
    #   replicas: 2

  assignments:
    build:
      context: ./assignments-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://db:27017
      - EXPRESS_PORT=3000

  submissions:
    build:
      context: ./submission-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=8000

  db:
    image: mongo
    ports:
      - "27017:27017"

